steps:
  - name: 'node:18'
    entrypoint: 'bash'
    args: ['-c', 'npm install && npm run build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', '--quiet']
timeout: '1600s'
